
  #JPA 설정
  spring:
    #PostgreSQL db 설정
    datasource:
      url: jdbc:h2:mem:testdb # H2 DB URL
      username: scott           # db 계정
      password: tiger             # db password
    #data.sql 파일 초기화 설정
    sql:
      #sql 파일 초기화 설정
      init:
        mode: always   # always 는 매번실행, never: 실행하지 않음
    #jpa 설정
    jpa:
      # ddl 파일에 대한 설정 규칙
      hibernate:
        ddl-auto: create-drop  # db에 대한 초기화 전략(none, create, create-drop, update, validate)
      properties:
        hibernate:
          show-sql: true # 쿼리문 출력
          format_sql: true # 쿼리문을 보기 좋게 춢력
      # 테이블 생성 후에 data.sql 파일을 실행하라
      defer-datasource-initialization: true
    h2:
      console:
        enabled:true


